using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using RestaurantSoftware.BL_Layer;
using RestaurantSoftware.Utils;
using RestaurantSoftware.DA_Layer;

namespace RestaurantSoftware.P_Layer
{
    public partial class Frm_QuanLyNhapHang : DevExpress.XtraEditors.XtraForm
    {
        HangHoa_BLL _hanghoaBLL = null;
        NhapHang_BLL _nhaphangBLL = null;
        DataTable dt = null;
        public Frm_QuanLyNhapHang()
        {
            InitializeComponent();
            dt = new DataTable();
            _nhaphangBLL = new NhapHang_BLL();
            _hanghoaBLL = new HangHoa_BLL();
            //load thông tin nhà cung cấp
            cmb_NhaCungCap.Properties.DataSource = new RestaurantSoftware.DA_Layer.RestaurantDBDataContext().NhaCungCaps;
            //load thông tin nhaann viên
            cmb_NhanVien.Properties.DataSource = new RestaurantSoftware.DA_Layer.RestaurantDBDataContext().NhanViens;
            // This line of code is generated by Data Source Configuration Wizard
            lue_TenHangHoa.Properties.DataSource = new RestaurantSoftware.DA_Layer.RestaurantDBDataContext().HangHoas;
        }
        private void Frm_QuanLyNhapHang_Load(object sender, EventArgs e)
        {
            LayThongNguyenLieu();
            LayDanhSachPhieuNhap();
            txt_MaPhieuNhap.Text = _nhaphangBLL.LayIdNhapHang();
            dt_NgayNhap.Text = DateTime.Now.ToShortDateString();
            _nhaphangBLL.LayDanhSachNguyenLieuNhap(grc_DanhSachNguyenLieuNhap);

        }
        private void LayThongNguyenLieu() {
            dt = Utils.Utils.ConvertToDataTable<HangHoa>(_hanghoaBLL.LayDanhSachHangHoa());
            lue_TenHangHoa.Properties.DataSource = dt;
            lue_TenHangHoa.Properties.DisplayMember = "tenhanghoa";
            lue_TenHangHoa.Properties.ValueMember = "id_hanghoa";
        }
       
        private void LayDanhSachPhieuNhap() {
            _nhaphangBLL.LayThongTinPhieuNhap(grc_PhieuNhap);
            _nhaphangBLL.LayDanhSachNguyenLieuNhap(grc_DanhSachNguyenLieuNhap);
            
        }
        private void btn_XemChiTiet_Click(object sender, EventArgs e)
        {
            Frm_NguyenLieu NguyenLieu = new Frm_NguyenLieu();
            //NguyenLieu.MdiParent = this;
            NguyenLieu.Show();
            //Form frm = this.ExistForm(typeof(P_Layer.Frm_QuanLyNhapHang));
            //if (frm != null)
            //{
            //    frm.Activate();
            //}
            //else
            //{
            //    Frm_NguyenLieu NguyenLieu = new Frm_NguyenLieu();
            //    NguyenLieu.MdiParent = this;
            //    NguyenLieu.Show();
            //}
           
        }

        private void btn_XemChiTietPhieuNhap_Click(object sender, EventArgs e)
        {
            Frm_DanhSachPhieuNhap PhieuNhap = new Frm_DanhSachPhieuNhap();
            PhieuNhap.Show();
        }
        private void btn_Xoa_Click(object sender, EventArgs e)
        {
            //_sucoBLL.XoaSuCo(int.Parse(txt_MaSuCo.Text));
            //Notifications.Answers("Xóa thành công!");
            //btn_LamMoi_Click(sender, e);
            _nhaphangBLL.XoaHoaDonNhapHang(int.Parse(txt_MaPhieuNhap.Text));
            Notifications.Answers("Xóa thành công");
            btn_LamMoi_Click(sender,e);
        }

        private void btn_XemTon_Click(object sender, EventArgs e)
        {
            Frm_NguyenLieuTon NguyenLieuTon = new Frm_NguyenLieuTon();
            NguyenLieuTon.Show();

        }
        // hàm làm mới
        private void btn_LamMoi_Click(object sender, EventArgs e)
        {
            //txt_MaPhieuNhap.Text = "";
            //cmb_NhanVien.Text = "";
            //dt_NgayNhap.Text = "";
            //cmb_TenNhaCungCap.Text = "";
            //txt_GhiChu.Text = "";

        }
        // hàm lưu
        private void btn_Luu_Click(object sender, EventArgs e)
        {

        }
        // hàm in
        private void btn_In_Click(object sender, EventArgs e)
        {
            SaveFileDialog saveFileDialog1 = new SaveFileDialog();
            saveFileDialog1.Filter = "File PDF|*.pdf|Excel|*.xls|Text rtf|*.rtf";
            saveFileDialog1.Title = "Xuất danh sách nhà cung cấp";
            if (saveFileDialog1.ShowDialog() == DialogResult.OK)
            {
                if (saveFileDialog1.FilterIndex == 1)
                    gridView1.ExportToPdf(saveFileDialog1.FileName);
                if (saveFileDialog1.FilterIndex == 2)
                    grc_DanhSachNguyenLieuNhap.ExportToXls(saveFileDialog1.FileName);
                if (saveFileDialog1.FilterIndex == 3)
                    grc_DanhSachNguyenLieuNhap.ExportToRtf(saveFileDialog1.FileName);
            }
        }
        // hàm xử lý thêm hàng hóa
        private void btn_ThemHangHoa_Click(object sender, EventArgs e)
        {
            Frm_NguyenLieu HangHoa = new Frm_NguyenLieu();
            HangHoa.Show();
        }

    }
}